"""Add SLA management fields to tickets

Revision ID: 1608d5597c20
Revises: e288cca136dd
Create Date: 2025-07-28 19:46:11.801133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1608d5597c20'
down_revision: Union[str, Sequence[str], None] = 'e288cca136dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types first
    impact_level_enum = sa.Enum('low', 'medium', 'high', 'critical', name='impact_level')
    business_priority_enum = sa.Enum('low', 'medium', 'high', 'urgent', name='business_priority')
    
    # Create the enum types
    impact_level_enum.create(op.get_bind())
    business_priority_enum.create(op.get_bind())
    
    # Add columns
    op.add_column('tickets', sa.Column('sla_target_hours', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('sla_breach_hours', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('first_response_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('resolution_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('escalation_level', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('escalation_notified', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('customer_impact', impact_level_enum, nullable=True))
    op.add_column('tickets', sa.Column('business_priority', business_priority_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'business_priority')
    op.drop_column('tickets', 'customer_impact')
    op.drop_column('tickets', 'escalation_notified')
    op.drop_column('tickets', 'escalation_level')
    op.drop_column('tickets', 'resolution_time')
    op.drop_column('tickets', 'first_response_time')
    op.drop_column('tickets', 'sla_breach_hours')
    op.drop_column('tickets', 'sla_target_hours')
    
    # Drop enum types
    sa.Enum(name='business_priority').drop(op.get_bind())
    sa.Enum(name='impact_level').drop(op.get_bind())
    # ### end Alembic commands ###
