"""Add city and state to FieldTech

Revision ID: 8c96e14baec8
Revises: 6c105c2a4195
Create Date: 2025-07-28 13:35:46.139537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c96e14baec8'
down_revision: Union[str, Sequence[str], None] = '6c105c2a4195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_techs', sa.Column('city', sa.String(), nullable=True))
    op.add_column('field_techs', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_techs', 'state')
    op.drop_column('field_techs', 'city')
    # ### end Alembic commands ###
