"""ensure_role_comparison_consistency

Revision ID: bc37b6f8eda6
Revises: 92eb88ef9904
Create Date: 2025-08-20 16:08:21.131820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc37b6f8eda6'
down_revision: Union[str, Sequence[str], None] = '92eb88ef9904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
