"""add must_change_password to users

Revision ID: e8b0d3557785
Revises: update_ticket_types_and_statuses
Create Date: 2025-07-30 18:59:54.906348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b0d3557785'
down_revision: Union[str, Sequence[str], None] = 'update_ticket_types_and_statuses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
