"""Add zip field to field_techs table

Revision ID: d579a11d32a3
Revises: 8c96e14baec8
Create Date: 2025-07-28 17:36:00.377856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd579a11d32a3'
down_revision: Union[str, Sequence[str], None] = '8c96e14baec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_techs', sa.Column('zip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_techs', 'zip')
    # ### end Alembic commands ###
